apiVersion: v1
kind: Pod
metadata:
  name: vulnerable-pod
  namespace: kube-system
spec:
  securityContext:
    runAsUser: 0   # ❌ Corre como root (viola "Require RunAsNonRootUser")
  containers:
    - name: app
      image: nginx:latest  # ❌ Usa una imagen con tag :latest
      securityContext:
        privileged: true    # ❌ Contenedor privilegiado
        runAsUser: 0        # ❌ Corre como root
  initContainers:
    - name: init
      image: busybox
      securityContext:
        runAsUser: 0        # ❌ Corre como root
  ephemeralContainers:
    - name: debug
      image: alpine
      securityContext:
        runAsUser: 0        # ❌ Corre como root